node:
  verbose: false
  port: 8100
  dataDir: /var/dreg/data/
  upstream:
    address: https://ish-ar.io
    insecure: true
  proxy:
    regex: ".*distribution.*"
  scheduler:
    address: http://scheduler:8000
  