node:
  verbose: false
  port: 8100
  dataDir: /var/dcache/data
  upstream:
    address: https://ish-ar.io
    insecure: true
  proxy:
    regex: ".*distribution.*"
  scheduler:
    address: http://scheduler:8000
  gc:
    maxAtimeAge: 24h
    interval: 2s
    maxDiskUsage: 100G
    minDiskFree: 20G
