node:
  verbose: false
  port: 8100
  dataDir: /var/dcache/data
  upstream:
    address: http://212.183.159.230
    insecure: true
  proxy:
    regex: ".*zip$"
  scheduler:
    address: http://scheduler:8000
  gc:
    maxAtimeAge: 24h
    interval: 6h
    maxDiskUsage: 100G
