version: "3.9"
services:
  node1:
    image: dpc:latest
    ports:
      - "8101:8100"
    entrypoint: /bin/sh
    command:
    - -c
    - /dpc node -c /mnt/node.yaml -i $$(hostname -i) -n $$(hostname) -v
    volumes:
      - ./configs:/mnt
    networks:
    - dpc

  node2:
    image: dpc:latest
    ports:
      - "8102:8100"
    entrypoint: /bin/sh
    command:
    - -c
    - /dpc node -c /mnt/node.yaml -i $$(hostname -i) -n $$(hostname) -v
    volumes:
      - ./configs:/mnt
    networks:
    - dpc

  scheduler:
    image: dpc:latest
    ports:
      - "8000:8000"
    command:
    - scheduler
    - -c
    - /mnt/scheduler.yaml
    volumes:
      - ./configs:/mnt
    networks:
    - dpc

networks:
  dpc: {}