version: "3.9"
services:
  node1:
    hostname: node1
    image: dcache:latest
    ports:
      - "8101:8100"
    entrypoint: /bin/sh
    command:
    - -c
    - /dcache node -c /mnt/node.yaml -i $$(hostname -i) -n $$(hostname) -v
    volumes:
      - ./configs:/mnt
    networks:
    - dcache

  node2:
    hostname: node2
    image: dcache:latest
    ports:
      - "8102:8100"
    entrypoint: /bin/sh
    command:
    - -c
    - /dcache node -c /mnt/node.yaml -i $$(hostname -i) -n $$(hostname) -v
    volumes:
      - ./configs:/mnt
    networks:
    - dcache

  scheduler:
    image: dcache:latest
    ports:
      - "8000:8000"
    command:
    - scheduler
    - -c
    - /mnt/scheduler.yaml
    volumes:
      - ./configs:/mnt
    networks:
    - dcache

networks:
  dcache: {}